### ISSUE TITLE
@Austin72 Would you please update? New CSGO offsets make Aimbot not work

### ISSUE THREAD

**Issue by wuwujia** [Austin72/Charlatano#10]
@Austin72 Would you please update? New CSGO offsets make Aimbot not work

**Comment by Kaeps** [comment]
@Austin72 Yes,Plz update...

**Comment by Kaeps** [comment]
@wuwujia If you upgrade, please let me know!

**Comment by Austin72** [comment]
Sadly I have no idea on how to update the offsets, let's all just wait for jire to do it.
Sorry.

**Comment by 4103chan** [comment]
Its not even the offsets that got changed, as the pattern scanner is still good and uses right patterns. SOme ingame stuff is radically changed (most notably a whole structure). I am trying to find a solution rn but I really am not good with low level programmming so I basically try and hope at this point. 

source:
https://www.unknowncheats.me/forum/counterstrike-global-offensive/228322-cs-update-2017-08-18t-spoonfeed-thread.html

**Comment by Austin72** [comment]
Should be fixed now.
