### ISSUE TITLE
how do u change trigger bot from head to body?

### ISSUE THREAD

**Issue by madefromrebel1** [Austin72/Charlatano#13]
cant seem to find the solution

**Comment by MoofMonkey** [comment]
wtf? you don't have eyes? if don't, then use search.
https://github.com/Jire/Charlatano/issues/363#issuecomment-324065190
Latest post about this

**Comment by andreva96** [comment]
.. he asked on both sides at the same time... no need to be agressive over it.

**Comment by MoofMonkey** [comment]
@andreva96, if you'll use search you'll find at least two posts with this question.

**Comment by Austin72** [comment]
added body/head targetting toggle.
