### ISSUE TITLE
Make aimbot/triggerbot work on team

### ISSUE THREAD

**Issue by hubslave** [Austin72/Charlatano#18]
(repost from https://github.com/Jire/Charlatano/issues/374)

Hi,
I'm playing on a server in which everyone (including me) is on T side, and I've yet to find a way to make the aimbot/triggerbot work on non-enemy players.

As you can see in my previous post I've tried a few things, so far to no avail. Any ideas?

**Comment by Austin72** [comment]
I've tried things and can't seem to get this to work as intended, however I will continue to try more and hopefully I will find you a solution.

**Comment by hubslave** [comment]
Thanks a lot.

**Comment by 4103chan** [comment]
In src/main/kotlin/com/charlatano/scripts/aim/General.kt
at line 88

```
internal fun Entity.canShoot()
		= spotted()
		&& !dormant()
		&& !dead()
		&& me.team() != team() /*<-- Make this toggable*/
		&& !me.dead()
		
internal fun Entity.canShootWall()
		= !dormant()
		&& !dead()
		&& me.team() != team() /*<-- Make this toggable*/
		&& !me.dead()
```
@Austin72

**Comment by Austin72** [comment]
added lol
