### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by VeNoMxKinG** [Austin72/Charlatano#24]
Sorry if this is a noob question but why am I getting this error? As far as i know ive done everything right.

![Error Message](https://user-images.githubusercontent.com/26808852/31153563-79b09f06-a867-11e7-8b16-ef9f4489fac9.png)

**Comment by Austin72** [comment]
Do you have Java and such installed?

**Comment by VeNoMxKinG** [comment]
Yes I do

**Comment by VeNoMxKinG** [comment]
There was something wrong with my Java installation so ive since reinstalled Java and it works so far
