### ISSUE TITLE
nice

### ISSUE THREAD

**Issue by YourFutureBoyfriend** [Austin72/Charlatano#28]
cool

**Comment by NegromancerR** [comment]
What exactly would this have done to my computer 😓

**Comment by MoofMonkey** [comment]
It's .NET executable, seems to not be obfuscated.

![image](https://user-images.githubusercontent.com/11695747/31848011-d1eec37e-b630-11e7-8dfb-e6e8e8364e68.png)

Here's sources: https://pastebin.com/xFKcvgGj

**Comment by MoofMonkey** [comment]
But where's it located?
